# Generated by Django 2.2.20 on 2021-04-25 15:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=100)),
                ('date', models.DateField()),
                ('posted_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Buy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('propid', models.CharField(max_length=200)),
                ('proptype', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('description', models.TextField(default='')),
                ('locality', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=50)),
                ('use', models.CharField(choices=[('commercial', 'Commercial'), ('residential', 'Residential')], max_length=50)),
                ('image1', models.ImageField(upload_to='uploads/')),
                ('image2', models.ImageField(upload_to='uploads/')),
                ('image3', models.ImageField(upload_to='uploads/')),
                ('posted_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proptype', models.CharField(blank=True, choices=[('apartment', 'Apartment'), ('villa', 'Villa')], max_length=50, null=True)),
                ('city', models.CharField(blank=True, choices=[('mumbai', 'Mumbai'), ('chennai', 'Chennai'), ('bengaluru', 'Bengaluru'), ('hyderabad', 'Hyderabad')], max_length=50, null=True)),
                ('use', models.CharField(blank=True, choices=[('commercial', 'Commercial'), ('residential', 'Residential')], max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('propid', models.CharField(max_length=200)),
                ('proptype', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('description', models.TextField(default='')),
                ('locality', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=50)),
                ('use', models.CharField(choices=[('commercial', 'Commercial'), ('residential', 'Residential')], max_length=50)),
                ('image1', models.ImageField(upload_to='uploads/')),
                ('image2', models.ImageField(upload_to='uploads/')),
                ('image3', models.ImageField(upload_to='uploads/')),
                ('posted_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Sell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('image0', models.ImageField(upload_to='userimages/')),
                ('image1', models.ImageField(upload_to='userimages/')),
                ('image2', models.ImageField(upload_to='userimages/')),
                ('posted_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('propertyid', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('due', models.IntegerField()),
                ('issues', models.CharField(blank=True, choices=[('home cleaning', 'Home Cleaning'), ('pest control', 'Pest Control'), ('sanitization', 'Sanitization'), ('plumbing', 'Plumbing'), ('other', 'Other')], default='', max_length=50, null=True)),
                ('request', models.CharField(blank=True, default='None', max_length=50, null=True)),
                ('email', models.EmailField(max_length=100)),
                ('posted_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
