# Generated by Django 2.2.20 on 2021-04-25 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosmoReal', '0002_remove_sell_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='sell',
            name='email',
            field=models.EmailField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
